 language:
      - java
  
  jdk:
      - oraclejdk8
      - openjdk7
  
  cache:
      directories:
          - $HOME/.m2
  dist:
      - trusty
  sudo:
      - false
  notifications:
      - email: always